function [rf]=fqrtAnalysis(rfTHO,rfABD,par,fq,statePSG,nev,binranges)
P_NUM=par.name;
width=20;
height=16;
unk=fq.unk;
nor=fq.nor;
evn=fq.evn;
NOR=par.st.nor;
OSA=par.st.osa;
CSA=par.st.csa;
MSA=par.st.msa;
HYP=par.st.hyp;
osaRg=(evn==OSA) & (unk==0);
csaRg=(evn==CSA) & (unk==0);
norRg=(nor==1) & (unk==0);
msaRg=(evn==MSA) & (unk==0);
hypRg=(evn==HYP) & (unk==0);
unkRg= (unk==1);
osaTHOrf=rfTHO(osaRg);
osaABDrf=rfABD(osaRg);
csaTHOrf=rfTHO(csaRg);
csaABDrf=rfABD(csaRg);
msaTHOrf=rfTHO(msaRg);
msaABDrf=rfABD(msaRg);
norTHOrf=rfTHO(norRg);
norABDrf=rfABD(norRg);
hypTHOrf=rfTHO(hypRg);
hypABDrf=rfABD(hypRg);
unkTHOrf=rfTHO(unkRg);
unkABDrf=rfABD(unkRg);
osaTHOrf=osaTHOrf(isnan(osaTHOrf)==0);
osaABDrf=osaABDrf(isnan(osaABDrf)==0);
msaTHOrf=msaTHOrf(isnan(msaTHOrf)==0);
msaABDrf=msaABDrf(isnan(msaABDrf)==0);
norTHOrf=norTHOrf(isnan(norTHOrf)==0);
norABDrf=norABDrf(isnan(norABDrf)==0);
csaTHOrf=csaTHOrf(isnan(csaTHOrf)==0);
csaABDrf=csaABDrf(isnan(csaABDrf)==0);
hypTHOrf=hypTHOrf(isnan(hypTHOrf)==0);
hypABDrf=hypABDrf(isnan(hypABDrf)==0);
rf.t.osa=osaTHOrf;
rf.t.csa=csaTHOrf;
rf.t.nor=norTHOrf;
rf.t.hyp=hypTHOrf;
rf.t.msa=msaTHOrf;
rf.a.osa=osaABDrf;
rf.a.csa=csaABDrf;
rf.a.nor=norABDrf;
rf.a.hyp=hypABDrf;
rf.a.msa=msaABDrf;
%% Histogram
binLen=length(binranges);
[hisOTHOglb] = histc(osaTHOrf,binranges);mOTHO=mean(osaTHOrf(osaTHOrf<=max(binranges)));sOTHO=std(osaTHOrf(osaTHOrf<=max(binranges)));
[hisOABDglb] = histc(osaABDrf,binranges);mOABD=mean(osaABDrf(osaABDrf<=max(binranges)));sOABD=std(osaABDrf(osaABDrf<=max(binranges)));
[hisCTHOglb] = histc(csaTHOrf,binranges);mCTHO=mean(csaTHOrf(csaTHOrf<=max(binranges)));sCTHO=std(csaTHOrf(csaTHOrf<=max(binranges)));
[hisCABDglb] = histc(csaABDrf,binranges);mCABD=mean(csaABDrf(csaABDrf<=max(binranges)));sCABD=std(csaABDrf(csaABDrf<=max(binranges)));
[hisMTHOglb] = histc(msaTHOrf,binranges);mMTHO=mean(msaTHOrf(msaTHOrf<=max(binranges)));sMTHO=std(msaTHOrf(msaTHOrf<=max(binranges)));
[hisMABDglb] = histc(msaABDrf,binranges);mMABD=mean(msaABDrf(msaABDrf<=max(binranges)));sMABD=std(msaABDrf(msaABDrf<=max(binranges)));
[hisNTHOglb] = histc(norTHOrf,binranges);mNTHO=mean(norTHOrf(norTHOrf<=max(binranges)));sNTHO=std(norTHOrf(norTHOrf<=max(binranges)));
[hisNABDglb] = histc(norABDrf,binranges);mNABD=mean(norABDrf(norABDrf<=max(binranges)));sNABD=std(norABDrf(norABDrf<=max(binranges)));
[hisHTHOglb] = histc(hypTHOrf,binranges);mHTHO=mean(hypTHOrf(hypTHOrf<=max(binranges)));sHTHO=std(hypTHOrf(hypTHOrf<=max(binranges)));
[hisHABDglb] = histc(hypABDrf,binranges);mHABD=mean(hypABDrf(hypABDrf<=max(binranges)));sHABD=std(hypABDrf(hypABDrf<=max(binranges)));
[hisUTHOglb] = histc(unkTHOrf,binranges);%mOTHO=mean(osaTHOrf);sOTHO=std(osaTHOrf);
[hisUABDglb] = histc(unkABDrf,binranges);%mOABD=mean(osaABDrf);sOABD=std(osaABDrf);
end