function [rt]=rtAnalysis(rtoTHO,rtoABD,par,rt,statePSG,nev,binranges,islog)
P_NUM=par.name;
unk=rt.unk;
nor=rt.nor;
evn=rt.evn;
NOR=par.st.nor;
OSA=par.st.osa;
CSA=par.st.csa;
MSA=par.st.msa;
HYP=par.st.hyp;
osaRg=find((statePSG==OSA) & (unk==0));
csaRg=find((statePSG==CSA) & (unk==0));
norRg=find((statePSG==NOR) & (unk==0));
msaRg=find((statePSG==MSA) & (unk==0));
hypRg=find((statePSG==HYP) & (unk==0));
unkRg=find(unk==1);
osaTHOrt=rtoTHO(osaRg);
osaABDrt=rtoABD(osaRg);
csaTHOrt=rtoTHO(csaRg);
csaABDrt=rtoABD(csaRg);
msaTHOrt=rtoTHO(msaRg);
msaABDrt=rtoABD(msaRg);
norTHOrt=rtoTHO(norRg);
norABDrt=rtoABD(norRg);
hypTHOrt=rtoTHO(hypRg);
hypABDrt=rtoABD(hypRg);
unkTHOrt=rtoTHO(unkRg);
unkABDrt=rtoABD(unkRg);
osaTHOrt=osaTHOrt(isnan(osaTHOrt)==0);
osaABDrt=osaABDrt(isnan(osaABDrt)==0);
msaTHOrt=msaTHOrt(isnan(msaTHOrt)==0);
msaABDrt=msaABDrt(isnan(msaABDrt)==0);
norTHOrt=norTHOrt(isnan(norTHOrt)==0);
norABDrt=norABDrt(isnan(norABDrt)==0);
csaTHOrt=csaTHOrt(isnan(csaTHOrt)==0);
csaABDrt=csaABDrt(isnan(csaABDrt)==0);
hypTHOrt=hypTHOrt(isnan(hypTHOrt)==0);
hypABDrt=hypABDrt(isnan(hypABDrt)==0);

width=20;
height=16;
%% Logarithmize
if islog==1
    [osaTHOrt ]=logmiz(osaTHOrt);
    [csaTHOrt ]=logmiz(csaTHOrt);
    [norTHOrt ]=logmiz(norTHOrt);
    [hypTHOrt ]=logmiz(hypTHOrt);
    [msaTHOrt ]=logmiz(msaTHOrt);
    [osaABDrt ]=logmiz(osaABDrt);
    [csaABDrt ]=logmiz(csaABDrt);
    [norABDrt ]=logmiz(norABDrt);
    [hypABDrt ]=logmiz(hypABDrt);
    [msaABDrt ]=logmiz(msaABDrt);
    upb=quantile([osaTHOrt; csaTHOrt; norTHOrt; hypTHOrt; msaTHOrt],0.95);
    lowb=quantile([osaTHOrt; csaTHOrt; norTHOrt; hypTHOrt; msaTHOrt],0.05);
    osaTHOrt=(osaTHOrt-lowb)/(upb-lowb);
    csaTHOrt=(csaTHOrt-lowb)/(upb-lowb);
    norTHOrt=(norTHOrt-lowb)/(upb-lowb);
    hypTHOrt=(hypTHOrt-lowb)/(upb-lowb);
    msaTHOrt=(msaTHOrt-lowb)/(upb-lowb);
    upb=quantile([osaABDrt; csaABDrt; norABDrt; hypABDrt; msaABDrt],0.95);
    lowb=quantile([osaABDrt; csaABDrt; norABDrt; hypABDrt; msaABDrt],0.05);
    osaABDrt=(osaABDrt-lowb)/(upb-lowb);
    csaABDrt=(csaABDrt-lowb)/(upb-lowb);
    norABDrt=(norABDrt-lowb)/(upb-lowb);
    hypABDrt=(hypABDrt-lowb)/(upb-lowb);
    msaABDrt=(msaABDrt-lowb)/(upb-lowb);
end
rt.t.osa=osaTHOrt;
rt.t.csa=csaTHOrt;
rt.t.nor=norTHOrt;
rt.t.hyp=hypTHOrt;
rt.t.msa=msaTHOrt;
rt.a.osa=osaABDrt;
rt.a.csa=csaABDrt;
rt.a.nor=norABDrt;
rt.a.hyp=hypABDrt;
rt.a.msa=msaABDrt;
end